/*
 * Created on 2024-01-13 ( 18:09:30 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.Project.SpringWeb.entities;

import java.io.Serializable;
import java.math.BigDecimal;

import jakarta.persistence.*;
import lombok.*;
/**
 * JPA entity class for "Students"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="STUDENTS", schema="SYS" )
@Data
@AllArgsConstructor
@RequiredArgsConstructor
@Getter
@Setter
public class Students implements Serializable {


	private static final long serialVersionUID = 1L;
	

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="ID")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pkey")
    @SequenceGenerator(name = "pkey", sequenceName = "pkey", allocationSize = 1)
    private BigDecimal slno ;
    

    @Column(name="ROLL", nullable=false)
    private BigDecimal roll ;

    //--- ENTITY DATA FIELDS 
    @Column(name="DEPT", length=255, nullable=false)
    private String     dept ;

    @Column(name="MARK", nullable=false)
    private Double     mark ;

    @Column(name="NAME", length=255, nullable=false)
    private String     name ;
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(roll);
        sb.append("|");
        sb.append(dept);
        sb.append("|");
        sb.append(mark);
        sb.append("|");
        sb.append(name);
        return sb.toString(); 
    } 

    @NonNull
    public Students(BigDecimal roll, String dept, Double mark, String name) {
        this.roll = roll;
        this.dept = dept;
        this.mark = mark;
        this.name = name;
    }

}
